/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Locale;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setColor(Home);
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{Details,Add_New,Delete_btn}, new JPanel[]{ind_2,ind_3, ind_4});
        add_employee.hide();
        Delete_panel.hide();
        Details_panel.hide();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_pane = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Details = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Add_New = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Delete_btn = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Search_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        add_employee = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Add = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_address = new javax.swing.JTextField();
        jTextField_rank = new javax.swing.JTextField();
        jTextField_name = new javax.swing.JTextField();
        jTextField_ohours = new javax.swing.JTextField();
        jTextField_whours = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        loadFile = new javax.swing.JButton();
        exportFile = new javax.swing.JButton();
        clearTable_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Home_panel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        Add1 = new javax.swing.JLabel();
        Delete_panel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        Add2 = new javax.swing.JLabel();
        Remove_btn = new javax.swing.JButton();
        Details_panel = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        Add3 = new javax.swing.JLabel();
        avgSal_btn = new javax.swing.JButton();
        maxSal_btn = new javax.swing.JButton();
        minSal_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        total_btn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane.setBackground(new java.awt.Color(23, 35, 51));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setBackground(new java.awt.Color(23, 35, 51));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Home");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 110, -1));

        Details.setBackground(new java.awt.Color(23, 35, 51));
        Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DetailsMouseReleased(evt);
            }
        });

        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Details");

        javax.swing.GroupLayout DetailsLayout = new javax.swing.GroupLayout(Details);
        Details.setLayout(DetailsLayout);
        DetailsLayout.setHorizontalGroup(
            DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addGap(0, 47, Short.MAX_VALUE))
        );
        DetailsLayout.setVerticalGroup(
            DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(DetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 120, -1));

        Add_New.setBackground(new java.awt.Color(23, 35, 51));
        Add_New.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Add_NewMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Add New");

        javax.swing.GroupLayout Add_NewLayout = new javax.swing.GroupLayout(Add_New);
        Add_New.setLayout(Add_NewLayout);
        Add_NewLayout.setHorizontalGroup(
            Add_NewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_NewLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        Add_NewLayout.setVerticalGroup(
            Add_NewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_NewLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Add_NewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(Add_New, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 120, -1));

        Delete_btn.setBackground(new java.awt.Color(23, 35, 51));
        Delete_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Delete_btnMousePressed(evt);
            }
        });

        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Remove");

        javax.swing.GroupLayout Delete_btnLayout = new javax.swing.GroupLayout(Delete_btn);
        Delete_btn.setLayout(Delete_btnLayout);
        Delete_btnLayout.setHorizontalGroup(
            Delete_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_btnLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        Delete_btnLayout.setVerticalGroup(
            Delete_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_btnLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Delete_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        side_pane.add(Delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 120, -1));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        side_pane.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 30, 40));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 590));

        jPanel2.setBackground(new java.awt.Color(71, 120, 197));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        Search_field.setBackground(new java.awt.Color(123, 156, 225));
        Search_field.setForeground(new java.awt.Color(255, 255, 255));
        Search_field.setBorder(null);
        Search_field.setCaretColor(new java.awt.Color(255, 255, 255));
        Search_field.setPreferredSize(new java.awt.Dimension(2, 20));
        Search_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_fieldKeyReleased(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Search_18px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(747, Short.MAX_VALUE)
                .addComponent(Search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Search_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 950, 50));

        add_employee.setBackground(new java.awt.Color(71, 120, 197));

        jPanel4.setBackground(new java.awt.Color(120, 168, 252));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add Employee");
        jPanel4.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(71, 120, 197));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(71, 120, 197));
        jButton1.setText("Save");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(71, 120, 197));
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setText("Name");
        jTextField8.setBorder(null);
        jTextField8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(71, 120, 197));
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setText("Address");
        jTextField9.setBorder(null);
        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(71, 120, 197));
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setText("Rank");
        jTextField10.setBorder(null);
        jTextField10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(71, 120, 197));
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setText("Work.hours");
        jTextField11.setBorder(null);
        jTextField11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(71, 120, 197));
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setText("Over.Hours");
        jTextField12.setBorder(null);
        jTextField12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextField13.setEditable(false);
        jTextField13.setBackground(new java.awt.Color(71, 120, 197));
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setText("ID");
        jTextField13.setBorder(null);
        jTextField13.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_employeeLayout = new javax.swing.GroupLayout(add_employee);
        add_employee.setLayout(add_employeeLayout);
        add_employeeLayout.setHorizontalGroup(
            add_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(add_employeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(jTextField11)
                    .addComponent(jTextField13)
                    .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(add_employeeLayout.createSequentialGroup()
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(add_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_address, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_rank, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_whours, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_ohours)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(add_employeeLayout.createSequentialGroup()
                        .addGroup(add_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        add_employeeLayout.setVerticalGroup(
            add_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_employeeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(add_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_rank, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_whours, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(add_employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ohours, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        getContentPane().add(add_employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 300, 540));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(242, 247, 247));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Launch dates for the items listed ");

        loadFile.setBackground(new java.awt.Color(71, 120, 197));
        loadFile.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        loadFile.setForeground(new java.awt.Color(71, 120, 197));
        loadFile.setText("Import from file");
        loadFile.setToolTipText("");
        loadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileActionPerformed(evt);
            }
        });

        exportFile.setBackground(new java.awt.Color(71, 120, 197));
        exportFile.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        exportFile.setForeground(new java.awt.Color(71, 120, 197));
        exportFile.setText("Export to file");
        exportFile.setToolTipText("");
        exportFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportFileActionPerformed(evt);
            }
        });

        clearTable_btn.setBackground(new java.awt.Color(71, 120, 197));
        clearTable_btn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        clearTable_btn.setForeground(new java.awt.Color(71, 120, 197));
        clearTable_btn.setText("Clear Table");
        clearTable_btn.setToolTipText("");
        clearTable_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTable_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loadFile)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exportFile, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(clearTable_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportFile, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearTable_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Rank", "WorkedHours", "OverTimeHours", "Payment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 650, 540));

        Home_panel.setBackground(new java.awt.Color(71, 120, 197));

        jPanel8.setBackground(new java.awt.Color(120, 168, 252));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Add1.setForeground(new java.awt.Color(255, 255, 255));
        Add1.setText("Home");
        jPanel8.add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        javax.swing.GroupLayout Home_panelLayout = new javax.swing.GroupLayout(Home_panel);
        Home_panel.setLayout(Home_panelLayout);
        Home_panelLayout.setHorizontalGroup(
            Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        Home_panelLayout.setVerticalGroup(
            Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(470, Short.MAX_VALUE))
        );

        getContentPane().add(Home_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 300, 540));

        Delete_panel.setBackground(new java.awt.Color(71, 120, 197));

        jPanel9.setBackground(new java.awt.Color(120, 168, 252));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Add2.setForeground(new java.awt.Color(255, 255, 255));
        Add2.setText("Remove");
        jPanel9.add(Add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        Remove_btn.setBackground(new java.awt.Color(71, 120, 197));
        Remove_btn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Remove_btn.setForeground(new java.awt.Color(71, 120, 197));
        Remove_btn.setText("Remove");
        Remove_btn.setToolTipText("");
        Remove_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Delete_panelLayout = new javax.swing.GroupLayout(Delete_panel);
        Delete_panel.setLayout(Delete_panelLayout);
        Delete_panelLayout.setHorizontalGroup(
            Delete_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(Delete_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Delete_panelLayout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addComponent(Remove_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );
        Delete_panelLayout.setVerticalGroup(
            Delete_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(470, Short.MAX_VALUE))
            .addGroup(Delete_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Delete_panelLayout.createSequentialGroup()
                    .addGap(249, 249, 249)
                    .addComponent(Remove_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addGap(250, 250, 250)))
        );

        getContentPane().add(Delete_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 300, 540));

        Details_panel.setBackground(new java.awt.Color(71, 120, 197));

        jPanel10.setBackground(new java.awt.Color(120, 168, 252));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Add3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        Add3.setForeground(new java.awt.Color(255, 255, 255));
        Add3.setText("Details");
        jPanel10.add(Add3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 30));

        avgSal_btn.setBackground(new java.awt.Color(71, 120, 197));
        avgSal_btn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        avgSal_btn.setForeground(new java.awt.Color(71, 120, 197));
        avgSal_btn.setText("Avg Salaries");
        avgSal_btn.setToolTipText("");
        avgSal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avgSal_btnActionPerformed(evt);
            }
        });

        maxSal_btn.setBackground(new java.awt.Color(71, 120, 197));
        maxSal_btn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        maxSal_btn.setForeground(new java.awt.Color(71, 120, 197));
        maxSal_btn.setText("Max Salary");
        maxSal_btn.setToolTipText("");
        maxSal_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxSal_btnMouseClicked(evt);
            }
        });
        maxSal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxSal_btnActionPerformed(evt);
            }
        });

        minSal_btn.setBackground(new java.awt.Color(71, 120, 197));
        minSal_btn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        minSal_btn.setForeground(new java.awt.Color(71, 120, 197));
        minSal_btn.setText("Min Salary");
        minSal_btn.setToolTipText("");
        minSal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minSal_btnActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane1);

        jScrollPane3.setViewportView(jTextPane2);

        jScrollPane4.setViewportView(jTextPane3);

        total_btn.setBackground(new java.awt.Color(71, 120, 197));
        total_btn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        total_btn.setForeground(new java.awt.Color(71, 120, 197));
        total_btn.setText("Total Salaries");
        total_btn.setToolTipText("");
        total_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_btnActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(jTextPane4);

        javax.swing.GroupLayout Details_panelLayout = new javax.swing.GroupLayout(Details_panel);
        Details_panel.setLayout(Details_panelLayout);
        Details_panelLayout.setHorizontalGroup(
            Details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(Details_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Details_panelLayout.createSequentialGroup()
                        .addGroup(Details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxSal_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minSal_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avgSal_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4)))
                    .addGroup(Details_panelLayout.createSequentialGroup()
                        .addComponent(total_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Details_panelLayout.setVerticalGroup(
            Details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Details_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(Details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avgSal_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(62, 62, 62)
                .addGroup(Details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minSal_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(54, 54, 54)
                .addGroup(Details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(maxSal_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(Details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addGap(106, 106, 106))
        );

        getContentPane().add(Details_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 300, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMousePressed
        // TODO add your handling code here:
        setColor(Home);
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{Details,Add_New,Delete_btn}, new JPanel[]{ind_2,ind_3, ind_4});
        add_employee.hide();
        Delete_panel.hide();
        Details_panel.hide();
        Home_panel.show();
    }//GEN-LAST:event_HomeMousePressed

    private void Add_NewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_NewMousePressed
        // TODO add your handling code here:
         setColor(Add_New);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{Details,Home,Delete_btn}, new JPanel[]{ind_2,ind_1, ind_4});
        Home_panel.hide();
        Delete_panel.hide();
        Details_panel.hide();
        add_employee.show();
    }//GEN-LAST:event_Add_NewMousePressed

    private void Delete_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_btnMousePressed
        // TODO add your handling code here:
          setColor(Delete_btn);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{Details,Add_New,Home}, new JPanel[]{ind_2,ind_3, ind_1});
        Home_panel.hide();
        add_employee.hide();
        Details_panel.hide();
        Delete_panel.show();
    }//GEN-LAST:event_Delete_btnMousePressed

    private void DetailsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailsMouseReleased
        // TODO add your handling code here:
          setColor(Details);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{Home,Add_New,Delete_btn}, new JPanel[]{ind_1,ind_3, ind_4});
        Home_panel.hide();
        add_employee.hide();
        Delete_panel.hide();
        Details_panel.show();
    }//GEN-LAST:event_DetailsMouseReleased

    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:

        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btn_exitMousePressed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String name = jTextField_name.getText();
        String address = jTextField_address.getText();
        String rank_String = jTextField_rank.getText();
        ////herr to get the inputs as text
        String id_String = jTextField_id.getText();
        String whours_String = jTextField_whours.getText();
        String ohours_String = jTextField_ohours.getText();
        /// now we parse the text of int,double values
        int id = Integer.parseInt(id_String);
        Integer rank = Integer.parseInt(rank_String);
        int whours = Integer.parseInt(whours_String);
        int ohours = Integer.parseInt(ohours_String);
        // vaildate enterd not empty
        String [] checkEmpty = {jTextField_name.getText(),jTextField_address.getText()};
            for (String check1 : checkEmpty) {
                if (check1 == null || check1.equals("")) {
                    throw new NullPointerException() ;
                }
            }
            if (rank == 3 || rank == 1 || rank == 2) {
            } else {
                throw new Exception("rank must be 1 , 2 , 3");
            }

        //// inital new employeee                                    *******************************************
        Employee e = new Employee(id, name, address, rank, whours, ohours);
        //add employee to table
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.addRow(new Object[] {e.getId(),e.getName(),e.getAddress(),e.getRank(),e.getHoursWorked(),e.getOvertimeHours(),e.getSalary()});

        } catch (NullPointerException e1) {
            JOptionPane.showMessageDialog(null, "All fields must me Enterd");
        }
        catch(NumberFormatException e2){
            JOptionPane.showMessageDialog(null, "ID , w.hours , o,Hours , rank must be Numbers");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }



    }//GEN-LAST:event_jButton1ActionPerformed

    private void Remove_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove_btnActionPerformed
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        try {
            //to check there is selected row not empty
            int selectedRow = jTable1.getSelectedRow();
            model.removeRow(selectedRow);

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "please select row to remove");
        }

    }//GEN-LAST:event_Remove_btnActionPerformed

    private void avgSal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avgSal_btnActionPerformed
        try {
        int numOfRows = jTable1.getRowCount();
        if (numOfRows < 1) throw new Exception("no table filed to calculate");
        double avg = 0 ;
        for (int i = 0; i < numOfRows; i++) {
            avg += Double.parseDouble(jTable1.getValueAt(i, 6).toString()); // 6 is colmn of salary

        }
        avg=avg/numOfRows;
        jTextPane3.setText(String.valueOf(avg));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_avgSal_btnActionPerformed

    private void maxSal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxSal_btnActionPerformed
        try {
            ArrayList<Double> list = new ArrayList<Double>();
            int numOfRows = jTable1.getRowCount();
            if (numOfRows < 1) throw new Exception("no table filed to calculate");
            for (int i = 0; i < numOfRows; i++) {
                 list.add(Double.parseDouble(jTable1.getValueAt(i, 6).toString())); // 6 is colmn of salary

             }
             double max = Collections.max(list);
             jTextPane1.setText(String.valueOf(max));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_maxSal_btnActionPerformed

    private void minSal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minSal_btnActionPerformed
        try {
           ArrayList<Double> list = new ArrayList<Double>();
           int numOfRows = jTable1.getRowCount();
           if (numOfRows < 1) throw new Exception("no table filed to calculate");
           for (int i = 0; i < numOfRows; i++) {
                list.add(Double.parseDouble(jTable1.getValueAt(i, 6).toString())); // 6 is colmn of salary
            }
            double min = Collections.min(list);
            jTextPane2.setText(String.valueOf(min));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_minSal_btnActionPerformed

    private void maxSal_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxSal_btnMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_maxSal_btnMouseClicked

    private void Search_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_fieldKeyReleased
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        String search = Search_field.getText().toLowerCase();
        //to sort rows
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));

    }//GEN-LAST:event_Search_fieldKeyReleased

    private void total_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_btnActionPerformed
        int numOfRows = jTable1.getRowCount();
        double total = 0 ;
        for (int i = 0; i < numOfRows; i++) {
            total += Double.parseDouble(jTable1.getValueAt(i, 6).toString()); // 3 is colmn of salary

        }
        jTextPane4.setText(String.valueOf(total));
    }//GEN-LAST:event_total_btnActionPerformed

    private void loadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            JFileChooser choose = new JFileChooser() ;
            choose.showOpenDialog(null);
            File f = choose.getSelectedFile();
        
            Scanner sc = new Scanner(f);
            while (sc.hasNext()) {
                //make every line as roe........
                String input = sc.next();
                String[] inputs = input.split(",");
               model.addRow(new Object[]{inputs[0],inputs[1],inputs[2],inputs[3],inputs[4],inputs[5],inputs[6]});


            }
            sc.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "no file selectd");
        }
       


    }//GEN-LAST:event_loadFileActionPerformed

    private void exportFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportFileActionPerformed
        try {
             File f = new File("export.txt");
             //check if exsistance
             if (!f.exists()) {
                f.createNewFile();
            }
             FileWriter fw = new FileWriter(f.getAbsoluteFile());
             BufferedWriter bw = new BufferedWriter(fw);

             int numOfRows = jTable1.getRowCount();
             int numOfCol = jTable1.getColumnCount();
             //check field is in table
             if (numOfRows < 1) throw new Exception("no table filed to export");
             for (int i = 0; i < numOfRows; i++) {
                 for (int j = 0; j < numOfCol; j++) {
                     bw.write(jTable1.getModel().getValueAt(i,j)+",");
                 }
                 bw.newLine();
            }
            bw.close(); fw.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_exportFileActionPerformed

    private void clearTable_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTable_btnActionPerformed
      try {
             
             DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
             int numOfRows = jTable1.getRowCount();
             //check field is in table
             if (numOfRows < 1) throw new Exception("table already empty");
             for (int i = 0; i < numOfRows; i++) { 
                     model.removeRow(i);
                 }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_clearTable_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }


    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }

    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));

        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add;
    private javax.swing.JLabel Add1;
    private javax.swing.JLabel Add2;
    private javax.swing.JLabel Add3;
    private javax.swing.JPanel Add_New;
    private javax.swing.JPanel Delete_btn;
    private javax.swing.JPanel Delete_panel;
    private javax.swing.JPanel Details;
    private javax.swing.JPanel Details_panel;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Home_panel;
    private javax.swing.JButton Remove_btn;
    private javax.swing.JTextField Search_field;
    private javax.swing.JPanel add_employee;
    private javax.swing.JButton avgSal_btn;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JButton clearTable_btn;
    private javax.swing.JButton exportFile;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_ohours;
    private javax.swing.JTextField jTextField_rank;
    private javax.swing.JTextField jTextField_whours;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JButton loadFile;
    private javax.swing.JButton maxSal_btn;
    private javax.swing.JButton minSal_btn;
    private javax.swing.JPanel side_pane;
    private javax.swing.JButton total_btn;
    // End of variables declaration//GEN-END:variables
}
